stages:
  - test

.test-base:
  stage: test
  image: webdevops/php-dev:${PHP_VERSION}-alpine
  variables:
    XDEBUG_MODE: coverage
  script:
    - composer install --no-plugins
    - vendor/bin/phpunit --colors=never --coverage-text --coverage-xml=coverage-${PHP_VERSION}.xml
  artifacts:
    reports:
      junit: coverage-${PHP_VERSION}.xml

test 8.2:
  extends: .test-base
  variables:
    PHP_VERSION: "8.2"

test 8.0:
  extends: .test-base
  variables:
    PHP_VERSION: "8.0"

test 7.4:
  extends: .test-base
  variables:
    PHP_VERSION: "7.4"

test 7.3:
  extends: .test-base
  variables:
    PHP_VERSION: "7.3"
